/* 
WEB-OLAP v1.0
Copyright 2020 Rassadnikov Evgeniy Alekseevich

This file is part of WEB-OLAP.

WEB-OLAP is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

WEB-OLAP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with WEB-OLAP.  If not, see <https://www.gnu.org/licenses/>.
 */
BEGIN
CREATE TABLE [dbo].[REP_DATA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](max) NOT NULL,
	[SYSNAME] [nvarchar](50) NULL,
	[HTML] [nvarchar](max) NULL,
	[DATA] [nvarchar](max) NULL,
	[USER_LAST_ID] [bigint] NULL,
 CONSTRAINT [PK_REP_DATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

CREATE TABLE [dbo].[REP_DATA_SET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REP_ID] [int] NOT NULL,
	[NAME] [nvarchar](250) NOT NULL,
	[SYSNAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_REP_DATA_SET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[REP_DATA_SET_VALUE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SET_ID] [int] NOT NULL,
	[VALUE] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_REP_DATA_SET_VALUE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

CREATE TABLE [dbo].[REP_USERS](
	[USER_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FIO] [nvarchar](500) NOT NULL,
	[LOGIN] [nvarchar](200) NOT NULL,
	[PASSWORD] [nvarchar](200) NOT NULL,
	[EMAIL] [nvarchar](500) NULL,
	[PHONE] [nvarchar](100) NULL,
	[SOL] [smallint] NULL,
 CONSTRAINT [PK_REP_USERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[REP_RIGHTS](
	[RIGHTS_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](500) NOT NULL,
	[SYSNAME] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_REP_RIGHTS] PRIMARY KEY CLUSTERED 
(
	[RIGHTS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[REP_USERS_RIGHTS](
	[RUR_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USER_ID] [bigint] NOT NULL,
	[RIGHT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REP_USERS_RIGHTS] PRIMARY KEY CLUSTERED 
(
	[RUR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
CREATE UNIQUE INDEX ULPU ON REP_USERS (LOGIN,PASSWORD); 

CREATE UNIQUE INDEX URU ON REP_USERS_RIGHTS (USER_ID,RIGHT_ID); 

CREATE INDEX RDU ON REP_DATA (USER_LAST_ID);

CREATE NONCLUSTERED INDEX [IX_REP_DATA_SET_VALUE] ON [dbo].[REP_DATA_SET_VALUE]
(
	[SET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

SET IDENTITY_INSERT [dbo].[REP_RIGHTS] ON;
INSERT [dbo].[REP_RIGHTS] ([RIGHTS_ID], [NAME], [SYSNAME]) VALUES (1, N'Редактирование формы', N'Edite');
INSERT [dbo].[REP_RIGHTS] ([RIGHTS_ID], [NAME], [SYSNAME]) VALUES (2, N'Просмотр формы', N'View');
INSERT [dbo].[REP_RIGHTS] ([RIGHTS_ID], [NAME], [SYSNAME]) VALUES (1002, N'Удаление формы', N'Delete');
INSERT [dbo].[REP_RIGHTS] ([RIGHTS_ID], [NAME], [SYSNAME]) VALUES (1004, N'Администрирование пользователей', N'Admin');
SET IDENTITY_INSERT [dbo].[REP_RIGHTS] Off;
SET IDENTITY_INSERT [dbo].[REP_USERS] ON;
INSERT [dbo].[REP_USERS] ([USER_ID], [FIO], [LOGIN], [PASSWORD], [EMAIL], [PHONE], [SOL]) VALUES (1, N'admin', N'admin', N'$2a$10$eSb3zD5nD4diakkyY.oRNesqQcd4EupReB2YhOMxZDaIWLQHUPsKy', NULL, NULL, 1);
SET IDENTITY_INSERT [dbo].[REP_USERS] Off;
SET IDENTITY_INSERT [dbo].[REP_USERS_RIGHTS] On;
INSERT [dbo].[REP_USERS_RIGHTS] ([RUR_ID], [USER_ID], [RIGHT_ID]) VALUES (1, 1, 1);
INSERT [dbo].[REP_USERS_RIGHTS] ([RUR_ID], [USER_ID], [RIGHT_ID]) VALUES (2, 1, 2);
INSERT [dbo].[REP_USERS_RIGHTS] ([RUR_ID], [USER_ID], [RIGHT_ID]) VALUES (10002, 1, 1002);
INSERT [dbo].[REP_USERS_RIGHTS] ([RUR_ID], [USER_ID], [RIGHT_ID]) VALUES (10003, 1, 1004);
SET IDENTITY_INSERT [dbo].[REP_USERS_RIGHTS] Off;
END;