SELECT U.LOGIN,
       U.FIO||'###'||TO_CHAR(U.USER_ID)  FIO,
       U.EMAIL,
       U.PHONE,
       R.NAME||'###'||TO_CHAR(R.RIGHTS_ID) RIGHTS_NAME,
       CASE WHEN U.FIO IS NOT NULL THEN 1
         ELSE 0
       END VALUE
FROM REP_RIGHTS R     
LEFT JOIN REP_USERS_RIGHTS UR
ON R.RIGHTS_ID=UR.RIGHT_ID    
LEFT JOIN REP_USERS U
ON UR.USER_ID=U.USER_ID
                
