DECLARE USER_ID_V NUMBER;
BEGIN
  USER_ID_V:=REP_USERS_ID_SQ.NEXTVAL;
  INSERT INTO REP_USERS (USER_ID, FIO, LOGIN, PASSWORD, EMAIL, PHONE, SOL) VALUES (USER_ID_V, 'guest', 'guest', '$2a$10$eSb3zD5nD4diakkyY.oRNesqQcd4EupReB2YhOMxZDaIWLQHUPsKy', NULL, NULL, 1);
  INSERT INTO REP_USERS_RIGHTS (RUR_ID, USER_ID, RIGHT_ID) VALUES (REP_USERS_RIGHTS_ID_SQ.NEXTVAL, USER_ID_V, 2);
  COMMIT;
END;
